version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=book_db
    networks:
      - win_api

networks:
  win_api:
    driver: bridge